dontfret/DontFretShop/urls.py
"""
Title: DontFretShop:urls
Author: Ben Frame
Date: 06/04/2020
"""

# Imports
from django.urls import path
from . import views

app_name = 'DontFretShop'  # Sub-program name

# Various URLs that the website can go to to access the various apps/web pages within this sub-program
urlpatterns = [
	path('', views.featuredProdCat, name='featuredProdCat'),  # The featured products page (the main menu/home page)
	path('all/', views.allProdCat, name='allProdCat'),  # The all products page
	path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),  # The category page which has a URL based on its slug
	path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),  # The product details page
]

dontfret/cart/urls.py
"""
Title: cart:urls
Author: Ben Frame
Date: 09/04/2020
"""

# Imports
from django.urls import path
from . import views

app_name = 'cart'  # Sub-app cart is part of the dontfret project

# Various URLs that the website can go to to access the various apps/web pages within this project
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name="add_cart"),  # Adding a particular product URL
    path('', views.cart_detail, name='cart_detail'),  # Viewing cart URL (main page of cart)
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),  # For decreasing quantity in cart
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),  # For binning item in cart
]

dontfret/dontfret/urls.py
from django.views.generic import TemplateView

"""
Title: dontfret:urls
Author: Ben Frame
Date: 06/04/2020
"""

# Imports
from django.contrib import admin
from django.urls import path, include
from DontFretShop import views
from django.conf import settings
from django.conf.urls.static import static  # Required for static About Us page

# Various URLs that the website can go to to access the various apps/web pages within this sub-program
urlpatterns = [
    path('admin/', admin.site.urls),  # URL location of admin features
    path('', views.index, name='index'),  # The index page
    path('DontFretShop/', include('DontFretShop.urls')),  # URL location of the shop
    path('search/', include('search_app.urls')),  # URL location of the search results
    path('cart/', include('cart.urls')),  # URL location of the cart
    path('order/', include('order.urls')),  # URL location of the order stats
    path('account/create/', views.signupView, name='signup'),  # URL location of the create account form
    path('account/create-store-assistant/', views.storeAssistantSignupView, name='signup-storeassistant'),  # URL location of the create store assistant form
    path('account/create-stock-controller/', views.stockControllerSignupView, name='signup-stockcontroller'),  # URL location of the create stock controller form
    path('account/edit-details/', views.editDetailsView, name='edit-details'),  # URL location of the edit account details form
    path('account/login/', views.signinView, name='signin'),  # URL location of the login page
    path('account/logout/', views.signoutView, name='signout'),  # URL for logging out
    path(r'^$', TemplateView.as_view(template_name="about-us.html"), name='about-us'),  # URL for the about us page (old way of doing things but still works)
]

# If debugging mode is on then stored files are still available
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dontfret/cart/models.py
"""
Title: cart:models
Author: Ben Frame
Date: 09/04/2020
"""

# Imports
from django.db import models
from DontFretShop.models import Product


# Determines attributes for Cart model
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    # Additional options/details for model
    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    # Return as string
    def __str__(self):
        return self.cart_id


# Determines attributes for Cart Item model (individual products in cart)
class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    # Additional options/details for model
    class Meta:
        db_table = 'CartItem'

    # Calculate sub total
    def sub_total(self):
        return self.product.price * self.quantity

    # Return as string
    def __str__(self):
        return self.product

dontfret/cart/forms.py
"""
Title: cart:forms
Author: Ben Frame
Date: 09/04/2020
"""

# Imports
from django import forms
from order.models import Order
from django.core.validators import RegexValidator  # Form for creation of User (and also as a template for editing user details)


# Form for getting card details for a purchase
class CardPaymentForm(forms.Form):
    cardNo = forms.CharField\
        (max_length=16, default='0000000000000000', verbose_name='Card No.',validators=[RegexValidator(r'^\d{1,10}$')])
    cardExpiryDateMonth = forms.CharField\
        (max_length=2, default='00', verbose_name='Card Expiry Date', validators=[RegexValidator(r'^\d{1,10}$')])
    cardExpiryDateYear = forms.CharField\
        (max_length=4, default='0000', verbose_name='Card Expiry Date', validators=[RegexValidator(r'^\d{1,10}$')])
    cardCCV = forms.CharField\
        (max_length=3, default='000', verbose_name='CCV No (Back Of Card)', help_text='The last 3 numbers on the back of your card', validators=[RegexValidator(r'^\d{1,10}$')])

    class Meta:
        model = Order  # Save data as part of a User model (as part of Python/Django)
        fields = ('cardNo', 'cardExpiryDateMonth', 'cardExpiryDateYear', 'cardCCV')  # Create fields

dontfret/cart/views.py
"""
Title: cart:views
Author: Ben Frame
Date: 09/04/2020
"""

# Imports
from django.contrib.auth.models import Permission, User
from django.core.mail import send_mail
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from dontfret.settings import EMAIL_HOST_USER
from DontFretShop.models import Product
from . models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
import stripe
from django.conf import settings
from order.models import Order, OrderLine


def _cart_id(request):
    cart = request.session.session_key  # Request the id of the cart particular to the current session (if there is one)

    if not cart:  # If there is no cart in the current session
        cart = request.session.create()

    return cart  # Return cart id


# Add product to cart (Add To Cart Button/Plus Button)
def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)  # Get selected item to be added to cart

    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))  # If a cart has already been established get cart ID
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)  # If a cart has not yet been established create one and get its ID
        )
        cart.save()  # Save the new cart

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)  # Get the item being added to cart

        if cart_item.quantity < cart_item.product.stock:  # Checks if there is enough stock to add to basket
            cart_item.quantity += 1  # Adds product to cart or increases the number of the same product in the cart

        cart_item.save()  # Save changes (if any) to cart
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()  # Save changes to cart

    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))  # Find the right cart
        cart_items = CartItem.objects.filter(cart=cart, active=True)  # Get the items in the cart

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)  # Calculate total price for each product
            counter += cart_item.quantity  # Calculate quantity of product(s)
    except ObjectDoesNotExist:  # Cart does not exist
        pass

    # Stripe Pay By Card functionality
    stripe.api_key = settings.STRIPE_SECRET_KEY  # My personal api key for my stripe account as found in settings.py
    stripe_total = int(total * 100)
    description = 'Don\'t Fret - New Order'
    data_key = settings.STRIPE_PUBLISHABLE_KEY  # My personal api key for my stripe account as found in settings.py

    if request.method == 'POST':
        try:  # Retrieve data from Stripe payment form
            token = request.POST['stripeToken']  # Retrieve payment token
            email = request.user.email  # Retrieve paying users email from account NOT form

            # Retrieve billing details
            billingName = request.POST['stripeBillingName']
            billingAddress1 = request.POST['stripeBillingAddressLine1']
            billingCity = request.POST['stripeBillingAddressCity']
            billingPostcode = request.POST['stripeBillingAddressZip']
            billingCountry = request.POST['stripeBillingAddressCountryCode']
            # Retrieve shipping details
            shippingName = request.POST['stripeShippingName']
            shippingAddress1 = request.POST['stripeShippingAddressLine1']
            shippingCity = request.POST['stripeShippingAddressCity']
            shippingPostcode = request.POST['stripeShippingAddressZip']
            shippingCountry = request.POST['stripeShippingAddressCountryCode']

            customer = stripe.Customer.create(  # Create customer with the retrieved info from Stripe payment form
                email=email,
                source=token
            )
            charge = stripe.Charge.create(  # Retrieve payment details
                amount=stripe_total,
                currency="gbp",
                description=description,
                customer=customer.id
            )

            # Creating the order
            try:
                order_details = Order.objects.create(  # Save the retrieved data to the order
                    token=token,
                    total=total,
                    emailAddress=email,
                    billingName=billingName,
                    billingAddress1=billingAddress1,
                    billingCity=billingCity,
                    billingPostcode=billingPostcode,
                    billingCountry=billingCountry,
                    shippingName=shippingName,
                    shippingAddress1=shippingAddress1,
                    shippingCity=shippingCity,
                    shippingPostcode=shippingPostcode,
                    shippingCountry=shippingCountry
                )

                order_details.save()  # Save changes to order now details have been added

                for order_line in cart_items:  # Retrieve order line details for each order line in order
                    ol = OrderLine.objects.create(
                        product=order_line.product.name,
                        quantity=order_line.quantity,
                        price=order_line.product.price,
                        order=order_details
                    )

                    ol.save()  # Save changes to order line each time an order line is added

                    # Reduce stock to reflect what has been purchased in the order
                    products = Product.objects.get(id=order_line.product.id)
                    products.stock = int(order_line.product.stock - order_line.quantity)  # Subtract ordered product from stock count
                    products.save()  # Save changes to stock levels
                    order_line.delete()

                    if products.stock < 4:  # Low stock warning if product has 3 or less left

                        # Gather the recipients list (all Stock Controllers)
                        users = User.objects.filter(groups__name='Stock Controller').values_list('email', flat=True)  # Retrieve all Stock Controller
                        recipients = list(users)  # Store them in a list of recipients

                        # Send each stock controller in list a low stock alert email
                        for email in recipients:
                            send_mail(
                                'Don\'t Fret - STOCK LOW',  # Subject
                                'Low stock warning for: ' + str(products),  # Content
                                EMAIL_HOST_USER,  # Email sender
                                [email],  # Email reciever
                                fail_silently=False,  # Raise exception if email fails
                            )

                    print('Your order has been placed!')  # Confirmation message in console (for debugging)

                return redirect('order:order_confirmed', order_details.id)  # Redirect to order confirmation page

            except ObjectDoesNotExist:  # Error
                pass

        except stripe.error.CardError as e:  # An error has occurred
            return False, e
    # /Stripe Pay By Card functionality

    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter,  # Display populated cart
                                             data_key=data_key, stripe_total=stripe_total, description=description))


# Reduce item quantity from cart (minus button)
def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))  # Get the user cart
    product = get_object_or_404(Product, id=product_id)  # Find the product to remove (else 404 error)
    cart_item = CartItem.objects.get(product=product, cart=cart)  # Find the specific item in cart based on the user cart and specific product

    if cart_item.quantity > 1:  # If the quantity is greater than one then simply decrease the quantity by one
        cart_item.quantity -= 1
        cart_item.save()  # Save changes
    else:
        cart_item.delete()  # Item already has quantity of one so remove item from cart entirely

    return redirect('cart:cart_detail')  # Return changes


# Fully remove item from cart regardless of quantity (bin button)
def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))  # Get the user cart
    product = get_object_or_404(Product, id=product_id)  # Find the product to remove (else 404 error)
    cart_item = CartItem.objects.get(product=product, cart=cart)  # Find the specific item in cart based on the user cart and specific product
    cart_item.delete()  # Remove item from cart regardless of quantity

    return redirect('cart:cart_detail')  # Return changes

dontfret/cart/templates/cart.html
{% extends "base.html" %}
{% load static %}

{% block metadescription %}
    This is your shopping cart where you can review your items and place your order.
{% endblock %}

{% block title %}
    Cart - Don't Fret
{% endblock %}

{% block content %}
    {% if not cart_items %}
        <div>
            <div class="text_center">
                <br>
                <h1 class="text-center my_title">
                    Your shopping cart is empty
                </h1>
                <br>
                <p class="text-center">
                    Please click <a href="{% url 'DontFretShop:allProdCat' %}">here</a> to continue shopping.
                </p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    Your shopping cart
                </h1>
                <br>
            </div>
        </div>
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th colspan="5">
                                Your items
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"></a>
                                </td>
                                <td class="text-left">
                                    <b>{{cart_item.product.name}}</b>
                                    <br>
                                    <i>(Product ID: {{cart_item.product.id}})</i>
                                    <br>
                                    Unit Price: £{{cart_item.product.price}}
                                    <br>
                                    Qty: {{cart_item.quantity}}
                                </td>
                                <td>
                                    £{{cart_item.sub_total}}
                                </td>
                                {% if cart_item.quantity < cart_item.product.stock %} <!-- If customer tries to buy more items than we have in stock -->
                                    <td>
                                        <a href="{% url 'cart:add_cart' cart_item.product.id %}"class="custom_a"><i class="fas fa-plus-circle custom_icon"></i></a>&nbsp;
                                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus-circle"></i></a>&nbsp;
                                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-trash-alt custom_icon"></i></a>
                                    </td>
                                {% else %}
                                    <td>
                                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus-circle"></i></a>&nbsp;
                                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-trash-alt custom_icon"></i></a>
                                    </td>
                                    <td></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="tabel my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th>
                                Checkout
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                Please review your shopping cart items before proceeding with the order payment.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                Your total is: <strong>£{{ total }}</strong>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="mx-auto">
                    {% if request.user.is_authenticated %} <!-- If user is logged in display payment option -->
                        <form method="POST">
                            {% csrf_token %} <!-- Additional security -->
                            {{ form }}
                            <input type="submit" value="Submit">
                        </form>

                        <form method="POST">
                            {% csrf_token %} <!-- Additional security -->
                            <script
                                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                data-key="{{ data_key }}"
                                data-ammount="{{ stripe_total }}"
                                data-name="Don't Fret"
                                data-description="{{ description }}"
                                data-image="{% static 'img/logo.png' %}"
                                data-locale="auto"
                                data-currency="gbp"
                                data-shipping-address="true"
                                data-billing-address="true"
                                data-zip-code="true"
                                data-email="{{ request.user.email }}">
                            </script>
                        </form>
                    {% endif %}
                    <a href="{% url 'DontFretShop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
                </div>
            </div>
        </div>
        <br>
    {% endif %}
{% endblock %}