dontfret/DontFretShop/urls.py
"""
Title: DontFretShop:urls
Author: Ben Frame
Date: 06/04/2020
"""

# Imports
from django.urls import path
from . import views

app_name = 'DontFretShop'  # Sub-program name

# Various URLs that the website can go to to access the various apps/web pages within this sub-program
urlpatterns = [
	path('', views.featuredProdCat, name='featuredProdCat'),  # The featured products page (the main menu/home page)
	path('all/', views.allProdCat, name='allProdCat'),  # The all products page
	path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),  # The category page which has a URL based on its slug
	path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),  # The product details page
]

dontfret/cart/urls.py
"""
Title: cart:urls
Author: Ben Frame
Date: 09/04/2020
"""

# Imports
from django.urls import path
from . import views

app_name = 'cart'  # Sub-app cart is part of the dontfret project

# Various URLs that the website can go to to access the various apps/web pages within this project
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name="add_cart"),  # Adding a particular product URL
    path('', views.cart_detail, name='cart_detail'),  # Viewing cart URL (main page of cart)
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),  # For decreasing quantity in cart
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),  # For binning item in cart
]

dontfret/dontfret/urls.py
from django.views.generic import TemplateView

"""
Title: dontfret:urls
Author: Ben Frame
Date: 06/04/2020
"""

# Imports
from django.contrib import admin
from django.urls import path, include
from DontFretShop import views
from django.conf import settings
from django.conf.urls.static import static  # Required for static About Us page

# Various URLs that the website can go to to access the various apps/web pages within this sub-program
urlpatterns = [
    path('admin/', admin.site.urls),  # URL location of admin features
    path('', views.index, name='index'),  # The index page
    path('DontFretShop/', include('DontFretShop.urls')),  # URL location of the shop
    path('search/', include('search_app.urls')),  # URL location of the search results
    path('cart/', include('cart.urls')),  # URL location of the cart
    path('order/', include('order.urls')),  # URL location of the order stats
    path('account/create/', views.signupView, name='signup'),  # URL location of the create account form
    path('account/create-store-assistant/', views.storeAssistantSignupView, name='signup-storeassistant'),  # URL location of the create store assistant form
    path('account/create-stock-controller/', views.stockControllerSignupView, name='signup-stockcontroller'),  # URL location of the create stock controller form
    path('account/edit-details/', views.editDetailsView, name='edit-details'),  # URL location of the edit account details form
    path('account/login/', views.signinView, name='signin'),  # URL location of the login page
    path('account/logout/', views.signoutView, name='signout'),  # URL for logging out
    path(r'^$', TemplateView.as_view(template_name="about-us.html"), name='about-us'),  # URL for the about us page (old way of doing things but still works)
]

# If debugging mode is on then stored files are still available
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dontfret/order/urls.py
"""
Title: order:urls
Author: Ben Frame
Date: 10/04/2020
"""

# Imports
from django.urls import path
from . import views

app_name = 'order'  # Sub-program name

# Established the URL paths used in sub-program
urlpatterns = [
    path('order_confirmed/<int:order_id>/', views.order_confirmed, name='order_confirmed'),  # Page for displaying order confirmation
    path('order_refund_rejected/<int:order_id>/', views.order_refund_rejected, name='order_refund_rejected'),  # Page for displaying order refund rejected notification
    path('order_refunded/<int:order_id>/', views.order_refunded, name='order_refunded'),  # Page for displaying order refund confirmation
    path('refund_order/<int:order_id>/', views.refundOrder, name='refund_order'),  # Page for calculating viability of refund
    path('history/', views.orderHistory, name='order_history'),  # For viewing users previous orders
    path('all_orders/', views.allOrderHistory, name='all_order_history'),  # For Store Assistant to view all orders placed
    path('<int:order_id>/', views.viewOrder, name='order_detail'),  # For viewing order details of an order
]

dontfret/order/models.py
"""
Title: order:models
Author: Ben Frame
Date: 10/04/2020
"""

# Imports
from django.db import models
from django.core.validators import RegexValidator


# Order attributes
class Order(models.Model):
    token = models.CharField(max_length=250, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Order Total (£)')
    emailAddress = models.EmailField(max_length=250, verbose_name='Email Address')
    order_date = models.DateTimeField(auto_now_add=True)  # Date of when order created is auto-generated
    is_refunded = models.BooleanField(default=False)
    # Billing address details
    billingName = models.CharField(max_length=250, blank=True)
    billingAddress1 = models.CharField(max_length=250, blank=True)
    billingCity = models.CharField(max_length=250, blank=True)
    billingPostcode = models.CharField(max_length=250, blank=True)
    billingCountry = models.CharField(max_length=250, blank=True)
    # Shipping address details
    shippingName = models.CharField(max_length=250, blank=True)
    shippingAddress1 = models.CharField(max_length=250, blank=True)
    shippingCity = models.CharField(max_length=250, blank=True)
    shippingPostcode = models.CharField(max_length=250, blank=True)
    shippingCountry = models.CharField(max_length=250, blank=True)
    # Payment Details (Regex Validator Used to Ensure Input is numerical)
    cardNo = models.CharField(max_length=16, default='0000000000000000', verbose_name='Card No.', validators=[RegexValidator(r'^\d{1,10}$')])
    #cardExpiryDate = models.CharField(max_length=4, default='0000', verbose_name='Card Expiry Date', validators=[RegexValidator(r'^\d{1,10}$')])
    #cardCCV = models.CharField(max_length=3, default='000', verbose_name='CCV No (Back Of Card)', validators=[RegexValidator(r'^\d{1,10}$')])

    # Additional options/details for model
    class Meta:
        db_table = 'Order'  # Save in a table called Order
        ordering = ['-order_date']  # Sort the table by the order date

    # Return as string
    def __str__(self):
        return str(self.id)  # Return order ID as string


# Order Line attributes
class OrderLine(models.Model):
    product = models.CharField(max_length=250)  # Name of product inside order
    quantity = models.IntegerField()  # The amount of that product purchased
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Price (£)')
    order = models.ForeignKey(Order, on_delete=models.CASCADE)  # When deleted remove all references in the order table

    # Additional options/details for model
    class Meta:
        db_table = 'OrderLine'  # Save in a table called OrderLine

    # Return sub-total that takes into account quantity purchased
    def sub_total(self):
        return self.quantity * self.price

    # Return as string
    def __str__(self):
        return self.product

dontfret/order/views.py
"""
Title: order:views
Author: Ben Frame
Date: 10/04/2020
"""

# Imports
from django.shortcuts import render, get_object_or_404
from .models import Order, OrderLine
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.core.mail import send_mail  # For email confirmations
from dontfret.settings import EMAIL_HOST_USER


# Display a confirmation message once an order has been placed
def order_confirmed(request, order_id):
    if order_id:
        customer_order = get_object_or_404(Order, id=order_id)  # Retrieve order with ID for display (or 404 error)
        email = request.user.email

        # Send confirmation email to customers saved email
        send_mail(
            'Don\'t Fret - Order Confirmation',  # Subject
            'Your order was successful! Please keep a note of your order number:\n' + str(order_id),  # Content
            EMAIL_HOST_USER,  # Email sender
            [email],  # Email reciever
            fail_silently=False,  # Raises exception should email fail
        )

    return render(request, 'order_confirmed.html', {'customer_order': customer_order})  # Display the order confirmed page with customer order details


# Display a confirmation message once an order has been placed
def order_refund_rejected(request, order_id):
    customer_order = get_object_or_404(Order, id=order_id)  # Retrieve order with ID for the order date (or 404 error)

    return render(request, 'order_refund_rejected.html', {'customer_order': customer_order})  # Display the order confirmed page with customer order details


# Display a confirmation message once an order has been placed
def order_refunded(request, order_id):
    if order_id:
        customer_order = get_object_or_404(Order, id=order_id)  # Retrieve order with ID for display (or 404 error)

    return render(request, 'order_refunded.html', {'customer_order': customer_order})  # Display the order confirmed page with customer order details


@login_required()  # Anonymous users CANNOT access this page
def orderHistory(request):
    if request.user.is_authenticated:  # Check if user is registered
        email = str(request.user.email)  # Store their email in string
        order_details = Order.objects.filter(emailAddress=email)  # Retrieve order details from that customers email

    return render(request, 'order/orders_list.html', {'order_details': order_details})  # Display order list


@login_required()  # Anonymous users CANNOT access this page
def allOrderHistory(request):
    if request.user.is_staff:  # Only display all orders if the user is confirmed staff memeber
        order_details = Order.objects.all()  # Retrieve all orders

    return render(request, 'order/orders_list_all.html', {'order_details': order_details})  # Display order list


@login_required()  # Anonymous users CANNOT access this page
def viewOrder(request, order_id):
    if request.user.is_authenticated:  # Check if the user is logged in and has permission
        email = str(request.user.email)  # Retrieve email and store as string
        order = Order.objects.get(id=order_id, emailAddress=email)  # Retrieve order
        order_lines = OrderLine.objects.filter(order=order)  # Retrieve order lines of the order

    return render(request, 'order/order_detail.html', {'order': order, 'order_items': order_lines})  # Display order details with order lines


@login_required()  # Anonymous users CANNOT access this page
def refundOrder(request, order_id):
    if request.user.is_authenticated:  # Check if the user is logged in and has permission
        email = str(request.user.email)  # Retrieve email and store as string
        order = Order.objects.get(id=order_id)  # Retrieve order
        now = datetime.now().date()  # Establish exact date and time

        if now.day - order.order_date.day > 1:  # If the order is older than 24hrs then set is refundable to false
            return render(request, 'order_refund_rejected.html', {'order': order})  # Display the order refund rejected page as it has been longer than 24hrs
        else:
            order.is_refunded = True  # Mark order as refunded
            order.save()  # Save changes to order attributes (is_refunded)

            return render(request, 'order_refunded.html', {'order': order})  # Display the order refunded page

dontfret/order/templates/order/order_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Order Details - Don't Fret
{% endblock %}

{% block content %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">Order Details</h1>
            <br>
            <table class="table table-bordered">
                <tr>
                    <td class="text-left" colspan="2">
                        <b>Order: </b>#{{ order.id }}<br>
                        <b>Date: </b>{{ order.order_date|date:"d M Y" }}<br>
                        <b>Order Total: </b>£{{ order.total }}<br>
                        {% if order.is_refunded == True %}
                        <b>Order Status: </b> Refunded
                        {% else %}
                        <b>Order Status: </b><i class="fas fa-check"></i> Complete
                        {% endif %}
                    </td>
                    <td class="text-left" colspan="2">
                        <b>Billing Address: </b><br>
                        {{ order.billingName }}<br>
                        {{ order.billingAddress1 }}<br>
                        {{ order.billingCity }}<br>
                        {{ order.billingPostcode }}<br>
                        {{ order.billingCountry }}<br>
                    </td>
                </tr>
                <tr>
                    <td><b>Product Description</b></td>
                    <td><b>Qty</b></td>
                    <td><b>Unit Price</b></td>
                    <td><b>Sub-Total</b></td>
                </tr>
                {% for item in order_items %}
                <tr>
                    <td>{{ item.product }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>£{{ item.price }}</td>
                    <td>£{{ item.sub_total }}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td class="text-right" colspan="3"><b>Total</b></td>
                    <td>£{{ order.total }}</td>
                </tr>
                <tr>
                    <td class="text-left" colspan="2">
                        <b>Shipping Address: </b><br>
                        {{ order.shippingName }}<br>
                        {{ order.shippingAddress1 }}<br>
                        {{ order.shippingCity }}<br>
                        {{ order.shippingPostcode }}<br>
                        {{ order.shippingCountry }}<br>
                    </td>
                    <td class="text-left" colspan="2">
                        <b>Payment Details: </b><br>
                        {% if order.is_refunded == True %}
                        The Order #{{ order.id }} has been refunded successfully.
                        {% else %}
                        The Order #{{ order.id }} has been paid for successfully.
                        {% endif %}
                    </td>
                </tr>
            </table>
            <button class="btn btn-secondary" onclick="window.print();"><i class="fas fa-print"></i>Print Order</button>
        </div>
    </div>
    <br>
    <br>
{% endblock %}

dontfret/order/templates/order/orders_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Order History - Don't Fret
{% endblock %}

{% block content %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">Order History</h1>
            <br>
            {% if order_details %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Order Number</th>
                        <th>Order Date</th>
                        <th>Total Amount</th>
                        <th>Status</th>
                        <th>Action</th>
                        <th>Refund Option</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in order_details %}
                    <tr>
                        <td>{{ order.id }}</td>
                        <td>{{ order.order_date|date:"d M Y" }}</td>
                        <td>{{ order.total }}</td>
                        {% if order.is_refunded == True %}
                        <td>Refunded</td>
                        {% else %}
                        <td><i class="fas fa-check"></i>&nbsp;Complete</td>
                        {% endif %}
                        <td><a href="{% url 'order:order_detail' order.id %}">View Order</a></td>
                        {% if order.is_refunded == True %}
                        <td style="color:green">Already Refunded!</td>
                        {% else %}
                        <td><a href="{% url 'order:refund_order' order.id %}">Refund Order</a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p>You have not placed any orders yet.<br><br><a href="{% url 'DontFretShop:featuredProdCat' %}" class="btn btn-secondary">
                Continue Shopping</a></p>
            {% endif %}
        </div>
    </div>
    <br>
    <br>
{% endblock %}

dontfret/order/templates/order/orders_list_all.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    All Orders - Don't Fret
{% endblock %}

{% block content %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">All Orders Placed</h1>
            <br>
            {% if order_details %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Order Number</th>
                        <th>Customer Order Name</th>
                        <th>Customer Order  Email</th>
                        <th>Order Date</th>
                        <th>Total Amount</th>
                        <th>Status</th>
                        <th>Action</th>
                        <th>Refund Option</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in order_details %}
                    <tr>
                        <td>{{ order.id }}</td>
                        <td>{{ order.billingName }}</td>
                        <td>{{ order.emailAddress }}</td>
                        <td>{{ order.order_date|date:"d M Y" }}</td>
                        <td>{{ order.total }}</td>
                        {% if order.is_refunded == True %}
                        <td>Refunded</td>
                        {% else %}
                        <td><i class="fas fa-check"></i>&nbsp;Complete</td>
                        {% endif %}
                        <td><a href="{% url 'order:order_detail' order.id %}">View Order</a></td>
                        {% if order.is_refunded == True %}
                        <td style="color:green">Already Refunded!</td>
                        {% else %}
                        <td><a href="{% url 'order:refund_order' order.id %}">Refund Order</a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p>You have not placed any orders yet.<br><br><a href="{% url 'DontFretShop:featuredProdCat' %}" class="btn btn-secondary">
                Back To Home Page</a></p>
            {% endif %}
        </div>
    </div>
    <br>
    <br>
{% endblock %}