dontfret/DontFretShop/urls.py
"""
Title: DontFretShop:urls
Author: Ben Frame
Date: 06/04/2020
"""

# Imports
from django.urls import path
from . import views

app_name = 'DontFretShop'  # Sub-program name

# Various URLs that the website can go to to access the various apps/web pages within this sub-program
urlpatterns = [
	path('', views.featuredProdCat, name='featuredProdCat'),  # The featured products page (the main menu/home page)
	path('all/', views.allProdCat, name='allProdCat'),  # The all products page
	path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),  # The category page which has a URL based on its slug
	path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),  # The product details page
]

dontfret/cart/urls.py
"""
Title: cart:urls
Author: Ben Frame
Date: 09/04/2020
"""

# Imports
from django.urls import path
from . import views

app_name = 'cart'  # Sub-app cart is part of the dontfret project

# Various URLs that the website can go to to access the various apps/web pages within this project
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name="add_cart"),  # Adding a particular product URL
    path('', views.cart_detail, name='cart_detail'),  # Viewing cart URL (main page of cart)
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),  # For decreasing quantity in cart
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),  # For binning item in cart
]

dontfret/dontfret/urls.py
from django.views.generic import TemplateView

"""
Title: dontfret:urls
Author: Ben Frame
Date: 06/04/2020
"""

# Imports
from django.contrib import admin
from django.urls import path, include
from DontFretShop import views
from django.conf import settings
from django.conf.urls.static import static  # Required for static About Us page

# Various URLs that the website can go to to access the various apps/web pages within this sub-program
urlpatterns = [
    path('admin/', admin.site.urls),  # URL location of admin features
    path('', views.index, name='index'),  # The index page
    path('DontFretShop/', include('DontFretShop.urls')),  # URL location of the shop
    path('search/', include('search_app.urls')),  # URL location of the search results
    path('cart/', include('cart.urls')),  # URL location of the cart
    path('order/', include('order.urls')),  # URL location of the order stats
    path('account/create/', views.signupView, name='signup'),  # URL location of the create account form
    path('account/create-store-assistant/', views.storeAssistantSignupView, name='signup-storeassistant'),  # URL location of the create store assistant form
    path('account/create-stock-controller/', views.stockControllerSignupView, name='signup-stockcontroller'),  # URL location of the create stock controller form
    path('account/edit-details/', views.editDetailsView, name='edit-details'),  # URL location of the edit account details form
    path('account/login/', views.signinView, name='signin'),  # URL location of the login page
    path('account/logout/', views.signoutView, name='signout'),  # URL for logging out
    path(r'^$', TemplateView.as_view(template_name="about-us.html"), name='about-us'),  # URL for the about us page (old way of doing things but still works)
]

# If debugging mode is on then stored files are still available
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dontfret/order/urls.py
"""
Title: order:urls
Author: Ben Frame
Date: 10/04/2020
"""

# Imports
from django.urls import path
from . import views

app_name = 'order'  # Sub-program name

# Established the URL paths used in sub-program
urlpatterns = [
    path('order_confirmed/<int:order_id>/', views.order_confirmed, name='order_confirmed'),  # Page for displaying order confirmation
    path('order_refund_rejected/<int:order_id>/', views.order_refund_rejected, name='order_refund_rejected'),  # Page for displaying order refund rejected notification
    path('order_refunded/<int:order_id>/', views.order_refunded, name='order_refunded'),  # Page for displaying order refund confirmation
    path('refund_order/<int:order_id>/', views.refundOrder, name='refund_order'),  # Page for calculating viability of refund
    path('history/', views.orderHistory, name='order_history'),  # For viewing users previous orders
    path('all_orders/', views.allOrderHistory, name='all_order_history'),  # For Store Assistant to view all orders placed
    path('<int:order_id>/', views.viewOrder, name='order_detail'),  # For viewing order details of an order
]

dontfret/search_app/urls.py
"""
Title: search_app:urls
Author: Ben Frame
Date: 07/04/2020
"""

# Imports
from django.urls import path
from . import views


app_name = 'search_app'  # Sub-program name


# Established the URL paths used in sub-program
urlpatterns = [
    path('', views.searchResult, name='searchResult')  # The results url (main and only search URL)
]

dontfret/DontFretShop/models.py
"""
Title: DontFretShop:models
Author: Ben Frame
Date: 06/04/2020
"""

# Imports
from django.db import models
from django.urls import reverse


# Determines attributes for the Category model
class Category(models.Model):
	name = models.CharField(max_length=250, unique=True)
	slug = models.SlugField(max_length=250, unique=True)
	description = models.TextField(blank=True)
	image = models.ImageField(upload_to='category', blank=True)

	# Additional options/details for model
	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	# Gets url for specific category
	def get_url(self):
		return reverse('DontFretShop:products_by_category', args=[self.slug])

	# Return as string
	def __str__(self):
		return '{}'.format(self.name)


# Determines attributes for the Product model
class Product(models.Model):
	name = models.CharField(max_length=250, unique=True)
	slug = models.SlugField(max_length=250, unique=True)  # Products unique URL
	brand = models.CharField(max_length=250, unique=False, default='Don\'t Fret Brand')  # Brand name defaults to the Don't Fret Brand if not given one
	description = models.TextField(blank=True)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)  # If product is deleted any other references are deleted too!
	price = models.DecimalField(max_digits=10, decimal_places=2)
	image = models.ImageField(upload_to='product', blank=True)
	stock = models.IntegerField()
	is_available = models.BooleanField(default=True)  # Available by default when created
	release_date = models.DateTimeField(auto_now_add=True)  # Store date of when product was first available
	updated_date = models.DateTimeField(auto_now=True)  # Store date of when product was last updated
	is_featured = models.BooleanField(default=False)  # Determines whether product is displayed in the featured section

	# Additional options/details for model
	class Meta:
		ordering = ('name',)
		verbose_name = 'product'
		verbose_name_plural = 'products'

	# Gets url for specific product
	def get_url(self):
		return reverse('DontFretShop:ProdCatDetail', args=[self.category.slug, self.slug])

	# Return as string
	def __str__(self):
		return '{}'.format(self.name)

dontfret/DontFretShop/forms.py
"""
Title: DontFretShop:forms
Author: Ben Frame
Date: 06/04/2020
"""

# Imports
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Form for creation of User (and also as a template for editing user details)
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=254, help_text='e.g. yourname@email.com')

    class Meta:
        model = User  # Save data as part of a User model (as part of Python/Django)
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')  # Create fields

dontfret/DontFretShop/views.py
"""
Title: DontFretShop:views
Author: Ben Frame
Date: 06/04/2020
"""

# Imports
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib.auth.models import Group, User
from .forms import SignUpForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout


# The index page is the first page that loads
def index(request):
	return redirect('DontFretShop:featuredProdCat')  # Navigate to the main menu


# View of all products
def allProdCat(request, c_slug=None):
	# Initialise variables
	c_page = None
	products_list = None

	# Gather list of products in category
	if c_slug == 'featured':
		products_list = Product.objects.filter(is_featured=True)
	if c_slug!=None:  # A specific category is selected
		c_page = get_object_or_404(Category, slug=c_slug)
		products_list = Product.objects.filter(category=c_page, is_available=True)
	else:  # All Products is selected (default)
		products_list = Product.objects.all().filter(is_available=True)

	# Paginator - For managing layout
	paginator = Paginator(products_list, 6)
	try:
		page = int(request.GET.get('page', '1'))
	except:
		page = 1
	try:
		products = paginator.page(page)
	except (EmptyPage, InvalidPage):
		products = paginator.page(paginator.num_pages)
	# /Paginator

	return render(request, 'DontFretShop/category.html', {'category': c_page, 'products': products})


# View of all featured products
def featuredProdCat(request, c_slug=None):
	# Initialise variables
	c_page = None

	# Gather list of featured products
	products_list = Product.objects.filter(is_featured=True)

	# Paginator - For managing layout
	paginator = Paginator(products_list, 6)
	try:
		page = int(request.GET.get('page', '1'))
	except:
		page = 1
	try:
		products = paginator.page(page)
	except (EmptyPage, InvalidPage):
		products = paginator.page(paginator.num_pages)
	# /Paginator

	return render(request, 'DontFretShop/category.html', {'category': c_page, 'products': products})


# When you click on a particular product
def ProdCatDetail(request, c_slug, product_slug):
	try:
		product = Product.objects.get(category__slug=c_slug, slug=product_slug)  # Retrieve selected product
	except Exception as ex:
		raise ex  # Display error

	return render(request, 'DontFretShop/product.html', {'product': product})  # Display specific product page


# For new customers signing up for an account
def signupView(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)  # Retrieve details from filled form

		if form.is_valid():
			user = form.save()  # Save the form

			if user is not None:
				user.save()
				username = form.cleaned_data.get('username')  # Get users username for ID
				#email = form.cleaned_data.get('email')  # Get users email for ID
				signup_user = User.objects.get(username=username)  # Keep the email identifier of the user signing up
				customer_group = Group.objects.get(name='Customer')  # Find the Customer group of users
				customer_group.user_set.add(signup_user)  # Add the user to the group

				login(request, user)  # Once user has registered log them in
				return redirect('DontFretShop:featuredProdCat')  # Redirect them to the main menu
			else:
				return redirect('signup')  # Unsuccessful, reload page
	else:
		form = SignUpForm()  # Display the sign up form again

	return render(request, 'accounts/signup.html', {'form': form})  # Go to signup page with form details


# For new stock controllers signing up for an account
def stockControllerSignupView(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)  # Retrieve details from filled form

		if form.is_valid():
			user = form.save()  # Save the form

			if user is not None:
				user.is_staff = True  # Give new staff member staff permissions
				user.save()  # Save changes to permissions
				username = form.cleaned_data.get('username')  # Get users username for ID
				signup_user = User.objects.get(username=username)  # Keep the email identifier of the user signing up
				staff_group = Group.objects.get(name='Stock Controller')  # Find the Customer group of users
				staff_group.user_set.add(signup_user)  # Add the user to the group

				login(request, user)  # Once user has registered log them in
				return redirect('DontFretShop:featuredProdCat')  # Redirect them to the main menu
			else:
				return redirect('signup')  # Unsuccessful, reload page
	else:
		form = SignUpForm()  # Display the sign up form again

	return render(request, 'accounts/signup-stockcontroller.html', {'form': form})  # Go to signup page with form details


# For new stock controllers signing up for an account
def storeAssistantSignupView(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)  # Retrieve details from filled form

		if form.is_valid():
			user = form.save()  # Save the form

			if user is not None:
				user.is_staff = True  # Allows stock controller to access the admin permissions of their group
				user.save()  # Save changes to permissions
				username = form.cleaned_data.get('username')  # Get users username for ID
				signup_user = User.objects.get(username=username)  # Keep the email identifier of the user signing up
				staff_group = Group.objects.get(name='Store Assistant')  # Find the Customer group of users
				staff_group.user_set.add(signup_user)  # Add the user to the group

				login(request, user)  # Once user has registered log them in
				return redirect('DontFretShop:featuredProdCat')  # Redirect them to the main menu
			else:
				return redirect('signup')  # Unsuccessful, reload page
	else:
		form = SignUpForm()  # Display the sign up form again

	return render(request, 'accounts/signup-storeassistant.html', {'form': form})  # Go to signup page with form details


# Sign in user by requesting they fill out their username and password
def signinView(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)  # Retrieve details from input login credentials

		if form.is_valid():  # If login credentials are filled in (regardless if they are correct)
			username = request.POST['username']  # Retrieve input username
			password = request.POST['password']  # Retrieve input password
			user = authenticate(username=username, password=password)  # Try to find a match for the input credentials

			if user is not None:  # A match has been found for the user trying to login
				login(request, user)  # User is now logged in for that session unless they sign out

				return redirect('DontFretShop:featuredProdCat')  # Navigate to the main menu
			else:  # No match was found for the user trying to login
				return redirect('signup')  # Redirect to the sign up page
	else:
		form = AuthenticationForm()  # Not all fields filled in, reload form

	return render(request, 'accounts/signin.html', {'form': form})


# Sign out currently logged in user
def signoutView(request):
	logout(request)  # Request user be logged out

	return redirect('signin')  # Redirect to sign in page


def editDetailsView(request):
	user = request.user  # Retrieve and store users details
	form = SignUpForm(request.POST or None, initial={
		'email': user.email,
		'first_name': user.first_name,
		'last_name': user.last_name})  # Save all to form variable (and auto-fill the form with user data using initial)

	if request.method == 'POST':

		if form.is_valid():  # If user input can be accepted

			# Change locally stored user details to their updated versions
			user.email = request.POST['email']
			#user.username = request.POST['email']  # A users username IS their email (a workaround so I can still use the default User model Python/Django provides)
			user.first_name = request.POST['first_name']
			user.last_name = request.POST['last_name']
			user.set_password(request.POST['password1'])

			User = user  # Local user is the same as global User
			User.save()  # Save the changes to logged in User's details

			return redirect('DontFretShop:featuredProdCat')  # Redirect them to the main menu
	else:
		form = SignUpForm(initial={
			'email': user.email,
			'first_name': user.first_name,
			'last_name': user.last_name})  # Display the sign up form again (auto-fill details again)

	return render(request, 'accounts/edit-details.html', {'form': form})  # Go to edit details page with form details

dontfret/DontFretShop/templates/about-us.html
{% extends "base.html" %}
{% load static %}

{% block metadescription %}
    About Don't Fret and how to contact us.
{% endblock %}

{% block title %}
    About Us/Contact Us - Don't Fret
{% endblock %}

{% block content %}
    <div class="container">
        <br>
        <h1 class="my_title text-center">About Us/Contact Us</h1>
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center my_customer_div">
                <br>
                <h2 class="my_title">About Us</h2>
                <br>
                <p>Our mission is to sell a whole bunch of guitars and stuff! We love guitars!</p>
                <br>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 bg-light">
                <div>
                    <br>
                    <h2 class="my_title">Contact Us</h2>
                    <p>Address: Don't Fret, 189 Cathedral Street, Glasgow, G4 3RA.</p>
                    <p>Telephone: 0141 4567367</p>
                    <p>Email: services@dontfret.com</p>
                    <br>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

dontfret/DontFretShop/templates/base.html
<!-- The template for most web pages -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="{% block metadescription %}{% endblock %}">
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"> <!-- Custom font (Roboto) -->
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<div class="container">
		<div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
			{% include 'top-navbar.html' %}
		</div>
		{% include 'header.html' %}
		{% include 'navbar.html' %}
		{% block content %}
		{% endblock %}
	</div>
	{% include 'footer.html' %}
	<script src="{% static 'js/jquery-3.4.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

dontfret/DontFretShop/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
	<p class="text-center">Don't Fret® - 2020</p>
	<p style="text-align: right">
		{% for group in request.user.groups.all %} <!-- Retrieve user group -->
    	{%  if 'Stock Controller' == group.name or 'Store Assistant' == group.name %}  <!-- If user is staff member allow creation of new staff -->
		<a href="{% url 'signup-storeassistant' %}">Create A New Store Assistant</a>
		 |
		<a href="{% url 'signup-stockcontroller' %}">Create A New Stock Controller</a>
		 |
		{% endif %}
		{% endfor %}
		<a href="{% url 'about-us' %}">About Us</a>
	</p>
</div>

dontfret/DontFretShop/templates/header.html
{% load static %}
<header>
	<center>
		<a href="{% url 'DontFretShop:featuredProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="Don't Fret"></a> <!-- Logo acts as home button -->
	</center>
</header>

dontfret/DontFretShop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
	  <li class="nav-item dropdown {% if 'DontFretShop' in request.path %}active{% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'DontFretShop:featuredProdCat' %}">Featured</a>
          <a class="dropdown-item" href="{% url 'DontFretShop:allProdCat' %}">All Products</a>
	      {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
		  {% endfor %}
        </div>
      </li>
      {% if item_count > 0 %} <!-- For displaying number of items in cart -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
      </li>
      {% endif %}
    </ul>
    {% for group in request.user.groups.all %}
    {%  if 'Stock Controller' == group.name %}
    <form class="form-inline my-2 my-lg-0" action="/admin/DontFretShop/product/">
      <button class="btn btn-secondary my-2 my-sm-0" style="background-color: #f44336">PRODUCT MANAGER</button>
    </form>
    &nbsp;
    {% elif 'Store Assistant' == group.name %}
    <form class="form-inline my-2 my-lg-0" action="/admin/auth/user/">
      <button class="btn btn-secondary my-2 my-sm-0" style="background-color: #f44336">USER MANAGER</button>
    </form>
    &nbsp;
    <form class="form-inline my-2 my-lg-0" action="{% url 'order:all_order_history' %}" method="get">
      <button class="btn btn-secondary my-2 my-sm-0" style="background-color: #f44336">VIEW ALL PLACED ORDERS</button>
    </form>
    &nbsp;
    {% endif %}
    {% endfor %}
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
      {% csrf_token %} <!-- Additional security -->
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>

dontfret/DontFretShop/templates/top-navbar.html
<div class="container">
    <div class="m_custom_menu">
        <ul>
            {% if request.user.is_authenticated and request.user.first_name %}
            <li>
                Welcome, <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ request.user.first_name }} <i class="fas fa-user-circle"></i></a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a href="{% url 'order:order_history' %}" class="dropdown-item">Order History</a>
                    <a href="{% url 'edit-details' %}" class="dropdown-item">Edit Account Details</a>
                </div>
            </li>
            <li>
                <a href="{% url 'signout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
            </li>
            <li>
                <a href="{% url 'signin' %}">Log In <i class="fas fa-sign-in-alt"></i></a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>